# images/single/mysql/Dockerfile

FROM mariadb:10.11

# Set default development credentials
ENV MYSQL_ROOT_PASSWORD=root_secret \
    MYSQL_DATABASE=app_db \
    MYSQL_USER=app_user \
    MYSQL_PASSWORD=app_secret

# Expose default MySQL port
EXPOSE 3306

